spring:
  profiles:
           active: dev
  servlet:
         multipart:
             max-file-size: 800MB
             max-request-size: 800MB
             enabled: true
  redis:
          database: 0
          host: 106.12.2.145:22
          port: 6379
          password:      # 密码（默认为空）
          timeout: 6000ms  # 连接超时时长（毫秒）
          jedis:
              pool:
                  max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
                  max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
                  max-idle: 10      # 连接池中的最大空闲连接
                  min-idle: 5       # 连接池中的最小空闲连接
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
    username: root
    password: 88888888
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
         cache: false
         mode: LEGACYHTML5

