


server:
  port: 80

camel:
  springboot:
    main-run-controller: true


spring:
  mail:
    host: smtp.qq.com
    username: 1060369102@qq.com
    password: yafamdcincujbfge
    properties:
     mail:
      smtp:
        auth: true
        timeout: 25000
        socketFactory.class: javax.net.ssl.SSLSocketFactory
    default-encoding: UTF-8
    port: 587
    debug: true


  application:
    name: spirng-boot-rabbitmq
  rabbitmq:
    host: 106.12.2.145
    port: 5672
    username: admin
    password: 123456